<div class="panel panel-default">
	<div class="panel-heading">
		<?=$title?>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">

                <?php if($erreur):?><?=$erreur?><?php endif;?>
                <form method="post" action="addUser.php">

                    <div class="form-group">
                        <label for="nom"> Nom : </label>
                        <input class="form-control" type="text" value="<?=$tableAuteurs['nom']?>" name="nom" id="nom" placeholder="nom"> 
                    </div>        

                    <div class="form-group">
                        <label for="prenom"> Prenom : </label>
                        <input class="form-control" type="text" value="<?=$tableAuteurs['prenom']?>" name="prenom" id="prenom" placeholder="prenom">
                    </div>

                    <div class="form-group">
                        <label for="email"> E-mail : </label>
                        <input class="form-control" type="email" value="<?=$tableAuteurs['email']?>" name="email" id="email" placeholder="email">
                    </div>
                    <div class="form-group">    
                        <label for="motDePasse"> Mot de passe :  </label>
                        <input class="form-control" type="password" name="motDePasse" id="motDePasse" placeholder="mot de passe">
                        <label for="confirmerMotDePasse"> Confirmer votre mot de passe :  </label>
                        <input class="form-control" type="password"  name="confirmerMotDePasse" id="confirmerMotDePasse" placeholder="mot de passe">
                    </div>
                    <div class="form-group">        
                        <label for="avatar"> Avatar : </label>
                        <input class="form-control" type="text" value="<?=$tableAuteurs['avatar']?>" name="avatar" id="lavatar">
                    </div>
                    <div class="form-group">
                        <label for="identifiant"> Identifiant : </label>
                        <input class="form-control" type="text" value="<?=$tableAuteurs['identifiant']?>" name="identifiant" id="identifiant">
                    </div>
                    
                    <div class="form-group">       
                        <label for="bio"> Biographie : </label>
                        <textarea class="form-control"  name="bio" id="bio"><?=$tableAuteurs['bio']?></textarea>
                    </div>

                    <div class="form-group">
                        <label for="role"> Role : </label>
                        <input class="form-control" type="text" value="<?=$tableAuteurs['role']?>" name="role" id="role" placeholder="position">
                    </div>

                    <input type="submit" value="Soumettre" class="btn btn-default">
                    <input type="reset" value="Réinitialiser" class="btn btn-default">
                </form>
            </div>
			<!-- /.col-lg-12 (nested) -->
		</div>
		<!-- /.row (nested) -->
	</div>
	<!-- /.panel-body -->
</div>





