<!--ceci correspond à la variable $vue-->
<h1> Ajout auteurs <h1>
<?php if($erreur):?>
    <p><?= $erreur; ?></p>
<?php endif;?>
        <form method="post" action="addUser.php">
        
            <label for="nom"> Nom : </label>
            <input type="text" value="<?=$tableAuteurs['nom']?>" name="nom" id="nom" placeholder="nom"> 
       
            <label for="prenom"> Prenom : </label>
            <input type="text" value="<?=$tableAuteurs['prenom']?>" name="prenom" id="prenom" placeholder="prenom">
        
            <label for="email"> E-mail : </label>
            <input type="email" value="<?=$tableAuteurs['email']?>" name="email" id="email" placeholder="email">
        
            <label for="motDePasse"> Mot de passe :  </label>
            <input type="password" name="motDePasse" id="motDePasse" placeholder="mot de passe">
            <label for="confirmerMotDePasse"> Confirmer votre mot de passe :  </label>
            <input type="password"  name="confirmerMotDePasse" id="confirmerMotDePasse" placeholder="mot de passe">
        
             
            <label for="avatar"> Avatar : </label>
            <input type="text" value="<?=$tableAuteurs['avatar']?>" name="avatar" id="lavatar">
        
        
            <label for="identifiant"> Identifiant : </label>
            <input type="text" value="<?=$tableAuteurs['identifiant']?>" name="identifiant" id="identifiant">
       
            <label for="bio"> Biographie : </label>
            <textarea name="bio" id="bio"><?=$tableAuteurs['bio']?></textarea>
       
            <label for="role"> Role : </label>
            <input type="text" value="<?=$tableAuteurs['role']?>" name="role" id="role" placeholder="position">
        
            <input type="submit" value="Soumettre">
            <input type="reset" value="Réinitialiser">
        </form>

       



