<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?=$title?></title>

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css
" rel="stylesheet">
</head>
  <body>

    <h1><?=$title?></h1>
    <?php

    include('tpl/'.$vue);
    
    ?>
  </body>

</html>
