<html>

<body>
    <div>
        <form action = "login.php" method = "post">
            <h2>Login</h2>
            
            <div>
                <label for="email"> E-mail : </label>
                <input type="email" name="email" id="email" placeholder="email">
            </div>
            <div>
                <label for="motDePasse"> Mot de passe :  </label>
            <input id="motDePasse" type="password" name="motDePasse" placeholder="mot de passe">
            </div>
            <input type="submit" value="Connexion">
        </form>
    </div>    
</body>
