<html>
<head>

</head>
<body>
    <section>
        <form action = "login.php" method = "post">
            <h2>Login</h2>
            
            <label for="identifiant"> Identifiant: </label>
            <input id="identifiant" type="text" name="identifiant" placeholder="identifiant">

            <label for="motDePasse"> Mot de passe :  </label>
            <input id="motDePasse" type="motDePasse" name="motDePasse" placeholder="mot de passe">

            <label for="confirmerMotDePasse"> Confirmer votre mot de passe :  </label>
            <input id="confirmerMotDePasse" type="confirmerMotDePasse" name="confirmerMotDePasse" placeholder="mot de passe">

            <input type="submit" value="Connexion">
        </form>
    </section>    
</body>
</html>