<section class="table-responsive">
    <h2>Client N°<?=$customerNumber?></h2>
    <table class="table">
        <thead>
            <th>Nom du client</th>
            <th>Nom du contact</th>
            <th>Prénom du contact</th>
            <th>Téléphone</th>
            <th>Adresse</th>
            <th>Employé référent</th>
            <th>Limite crédit</th>
        </thead>
        <tbody>
            <tr>
                <td><?=$result['customerName']?></td>
                <td><?=$result['contactFirstName']?></td>
                <td><?=$result['contactLastName']?></td>
                <td><?=$result['phone']?></td>
                <td><?=$result['addressLine1']?><br/><?=$result['addressLine2']?><br/><?=$result['postalCode']?> <?=$result['city']?> - <?=$result['country']?></td>
                <td><?=$result['salesRepEmployeeNumber']?></td>
                <td><?=$result['creditLimit']?> €</td>
            </tr>   
        </tbody>
    </table>
    <h2>Toutes les commandes du client</h2>
    <table id="tableDonnee" class="table">
        <thead>
            <th>Num</th>
            <th>Date</th>
            <th>Date livraison</th>
            <th>Date d'envoi</th>
            <th>Status</th>
            <th>Commentaires</th>
        </thead>
        <tbody>
            <?php foreach($cmds as $index=>$cmd):?>
                <tr>
                    <td><a href="bc.php?id=<?=$cmd['orderNumber']?>"><?=$cmd['orderNumber']?></a></td>
                    <td><?=$cmd['orderDate']?></td>
                    <td><?=$cmd['requiredDate']?></td>
                    <td><?=$cmd['shippedDate']?></td>
                    <td><?=$cmd['status']?></td>
                    <td><?=$cmd['comments']?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>