<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--><title><?=$title?></title>

    Bootstrap core CSS 
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    Datatable
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css
" rel="stylesheet">
  <head>-->
   <h1>Nouveau Blog</h1>  
  </head>

  <body>

 
  </body>

</html>
